# Generated by Django 5.0.7 on 2025-08-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
